export const COMMON_CURRENCIES = [
  { code: "TWD", label: "TWD 台幣" },
  { code: "JPY", label: "JPY 日圓" },
  { code: "USD", label: "USD 美元" },
  { code: "EUR", label: "EUR 歐元" },
  { code: "KRW", label: "KRW 韓元" },
  { code: "HKD", label: "HKD 港幣" },
  { code: "CNY", label: "CNY 人民幣" },
  { code: "GBP", label: "GBP 英鎊" },
  { code: "AUD", label: "AUD 澳幣" },
  { code: "CAD", label: "CAD 加幣" },
  { code: "SGD", label: "SGD 新加坡幣" },
  { code: "THB", label: "THB 泰銖" },
  { code: "VND", label: "VND 越南盾" },
  { code: "MYR", label: "MYR 馬幣" },
  { code: "IDR", label: "IDR 印尼盾" },
  { code: "PHP", label: "PHP 披索" },
  { code: "MOP", label: "MOP 澳門幣" },
  { code: "NZD", label: "NZD 紐西蘭幣" },
  { code: "CHF", label: "CHF 瑞士法郎" },
];
